### ISSUE TITLE
Redux-simple-router and React-Router replaceState interactions

### ISSUE THREAD

**Issue by ingro** [jlongster/redux-simple-router#69] opened 2015-12-03 13:34 UTC
Hello! I need to implement authentication mechanics to my application and so instead of starting from scratch I've used [React-Router auth-flow example](https://github.com/rackt/react-router/tree/master/examples/auth-flow) as example.

I'm facing a strange problem: from the `Login` component (roughly the same as the example above) I should be able to redirect to the previous visited route if auth is successfull:

```javascript
if (loggedIn) {
   const { location, history } = this.props;

   if (location.state && location.state.nextPathname) {
       history.replaceState(null, location.state.nextPathname);
   } else {
       history.replaceState(null, '/');
   }
}
``` 

This path should be stored inside the location state object by the `onEnter` hook on a protected route:

```javascript
function requireAuth(nextState, replaceState) {
    if (! isLoggedIn()) {
        replaceState({ nextPathname: nextState.location.pathname }, '/login');
    }
}
```

If I use this logic with `redux-simple-route`, inside the `Login` component the props `this.location.state` is `null`, while, if disabled, contains the right nextPathname property.

I think I've narrowed down the problem to these lines of `redux-simple-router` (68-71): 

```javascript
if(lastChangeId !== routing.changeId) {
  lastChangeId = routing.changeId;
  history.pushState(null, routing.path);
}
```

It pushes the route to history (which it should be not necessary) and doesn't pass the state in the process.

A simple fix would be setting `changeId` in the initial state to `0` but I don't know if it may cause other things to stop working...

**Comment by kjbekkelund** [comment] 2015-12-03 14:03
This should be solved in master. There's been quite a few commits lately, so hopefully we'll see a new version soon.

Btw, while waiting for a new release I depend on master instead of `0.0.10`:

```
"redux-simple-router": "https://github.com/jlongster/redux-simple-router.git#master",
```

**Comment by ingro** [comment] 2015-12-03 14:15
Thanks I will try with master so!

**Comment by gavacho** [comment] 2015-12-04 04:14
When I update my package.json like that, webpack starts to fail:

```
ERROR in ./app/main.js
Module not found: Error: Cannot resolve module 'redux-simple-router' in /Users/ken/heroproof/app
 @ ./app/main.js 79:25-55
```

When I look at the package.json in node_modules/redux-simple-router I see `"main": "lib/index"` but I don't see any directory `lib`.

**Comment by kjbekkelund** [comment] 2015-12-04 05:03
Ah, my bad, I totally forgot it must be built :/ Sorry. You can fix this with:

```
cd node_modules/redux-simple-router
npm install
npm run build
```

So not exactly very nice, but it helps if you want to test it.

@jlongster I really think it's about time with a new release. Lots of new stuff in master right now (and I really should stop telling people to use master — it's not a very good recommendation :/)

**Comment by gavacho** [comment] 2015-12-04 16:57
Thanks for responding, @kjbekkelund.  Count me among those eager for a new release.

When I build in-place per you instructions, I end up with a file at `lib/index.js`, so that's good.  Unfortunately the file is still es6.  It's not *identical* to `src/index.js`, but it's still got all the `const` and `=>`.  I believe the file at `lib/index.js` is intended to be es5.

**Comment by gavacho** [comment] 2015-12-04 17:04
Sorry, I figured out that `npm run build` was calling the globally installed babel and I guess mine was out of date.  When I change the command to `mkdir -p lib && node_modules/.bin/babel ./src/index.js --out-file ./lib/index.js`, it works.  Thanks!

**Comment by gavacho** [comment] 2015-12-04 17:06
I spoke too soon, that didn't fix it.

**Comment by gavacho** [comment] 2015-12-04 17:11
It was the missing `.babelrc` file.

**Comment by jlongster** [comment] 2015-12-04 17:12
Why does it need to be built? Does installing from a github repo not run the post-install hooks?

**Comment by jlongster** [comment] 2015-12-04 17:17
> @jlongster I think it's about time with a new release. Lots of new stuff in master right now (and I really should stop telling people to use master — it's not a very good recommendation :/)

Agreed. I really wanted to fix the devtools issue, and there were a few coding style tweaks I was going to do. I personally haven't been update to play with master yet.

I can work on it in the next day or two. I really wanted to to at least look at the devtools issue.

**Comment by gavacho** [comment] 2015-12-04 17:17
@jlongster I think it's because the build is setup to occur during the [`prepublish` hook] (https://github.com/jlongster/redux-simple-router/blob/master/package.json#L23)

**Comment by jlongster** [comment] 2015-12-04 17:19
Ah right. I wonder if there's a way to get it working from a straight git install.

**Comment by jlongster** [comment] 2015-12-07 01:42
Can you try master? I'm going to close this this week unless you can reproduce the issue.

**Comment by kjbekkelund** [comment] 2015-12-11 19:31
Closed this, let us know if you still have problems

**Closed** 2015-12-11 19:30 UTC

**Comment by ingro** [comment] 2015-12-12 12:38
Sorry for the late reply, anyway 1.0 fixed my problem, thanks for the fix!
