### ISSUE TITLE
compatible with HashHistory?

### ISSUE THREAD

**Issue by box-turtle** [jlongster/redux-simple-router#12] opened 2015-11-09 18:19 UTC
I see a strange behavior if I try to use this with HashHistory and call syncReduxAndRouter.

The queryKey param (http://rackt.org/history/stable/HashHistoryCaveats.html) seems to change every second or so, changing in the URL bar and I think it's reloading the route every second as well.

![image](https://cloud.githubusercontent.com/assets/3999743/11042322/60cf6c34-86e4-11e5-92cc-4580eb649c88.png)

I get this warning in console: 

Warning: You cannot PUSH the same path using hash history

It's possible this is something with my app, but I didn't see it when using redux-router.

I like this API much better! Just curious if anyone else has seen this behavior.

**Comment by kadmil** [comment] 2015-11-12 14:33
I've catch this too.

**Comment by kadmil** [comment] 2015-11-12 14:40
Looks like side-effect of putting location-with-hash back to history. That should be it: then you update history of createHashHistory it tries to save `pushState` to hash and trigger updates.

**Comment by kadmil** [comment] 2015-11-12 14:43
![image](https://cloud.githubusercontent.com/assets/4445523/11121071/e039b6be-8964-11e5-82f0-45f5917c447d.png)
We've forgot about `key` part

**Comment by jlongster** [comment] 2015-11-12 15:13
Thanks all, I'll try to look at this more today. Admittedly I don't understand the `key` part of HashHistory.

**Comment by kadmil** [comment] 2015-11-12 15:17
It's something they put as query param to save previous state, and it's quite puzzling.

**Comment by zeroshine** [comment] 2015-11-12 16:02
I have the same problem too.
I find it's the problem of the function locationToString
In createHashHistory routing path is /xxxx, not include /#
but in locationToString will return location.hash include /#
so it can't avoid history pushstate

**Comment by jlongster** [comment] 2015-11-12 21:48
There's a PR for this: #23. I'd like to find a prettier way to fix, but looks like we basically just need to do something different in `locationToString` if using hashHistory. Will look at it more soon.

**Comment by amccloud** [comment] 2015-11-13 07:36
@jlongster Does that PR disregard all query params from being stored in state?

Looks like the key param `_k` never makes it into the store so every time the store changes the syncing thinks the location changed because the key param is present in `window.location`. We could strip the key param from `window.location` before comparing to what is in the store. The key param can be renamed from `_k` so this would likely need to be a customizable configuration to handle it correctly.

I wish they would just remove state from history :disappointed:

**Comment by zeroshine** [comment] 2015-11-14 16:50
@amccloud 
In PR#23, I just write a simple regex in ~locationToString~ function to match the string wihout ~~?~~.
You can check its diff for more information
A simple fix it way is just copy ~~syncReduxAndRouter~~ to your source code
and use your customize ~~locationToString~~

**Comment by jlongster** [comment] 2015-11-18 05:12
Hey all, I just started working on a basic example, and I tried hash history with it and it worked fine: https://github.com/jlongster/redux-simple-router/pull/35

What other steps do I need to do to recreate this issue?

**Comment by jlongster** [comment] 2015-11-19 04:17
@kadmil @box-turtle I still can't fully reproduce this error: "Warning: You cannot PUSH the same path using hash history"

We do need to fix *something* here, but it should never push the same path. Because if history changes because a `Link` was clicked, it will fire `history.listen`, and will do something like `if("/foo" !== "/#/bar?_k=blah")` which will trigger a store update. *However* it updates the store with the location from history, which is actually only `/bar`.  That update will trigger another check in the store listener, and will compare `"/bar" !== "/#/bar?_k=blah"` because it gets the location from `window.location`. That fires another `pushState`, but when that history listener runs it will compare `"/bar" !== "/bar"` and stop there.

So there is a problem: the updating process should stop in the store listener. We can't assume that `window.location` is the same as the location given from the history object when using hash history. But I can't reproduce exactly what you say, and I'm curious why not.

**Comment by jlongster** [comment] 2015-11-19 04:21
@ryanflorence @mjackson Sorry to pull you in like this, but do you know of a robust way to get the current URL from a `history` object? Right now when I need to compare it against the URL in the redux store, I use `window.location` but that doesn't work when using hash history. I'd like for a way to do `history.getCurrentLocation`, which last I looked is not exported (I'll check again).

**Comment by heydemo** [comment] 2015-11-22 22:16
@jlongster You can recreate the  same path warning if you set

` createHashHistory({ queryKey: false });`

locationToString is including the leading #/  in the path so it will appear 'new.'

locationToString -  '/#/mypath';

routing.path - '/mypath'

**Comment by amccloud** [comment] 2015-11-22 22:20
@heydemo checkout PR #40

**Comment by jlongster** [comment] 2015-11-24 17:47
This should be fixed with #40, which I just pushed out with 0.0.9

**Closed by jlongster** 2015-11-24 17:47 UTC

**Comment by benjamine** [comment] 2016-11-24 04:43
this seem to be alive again, exactly 1yr after closing (coincidence :O ?)
getting this with
```
    "immutable": "^3.8.1",
    "react": "15.4.1",
    "react-dom": "15.4.1",
    "react-immutable-proptypes": "^2.1.0",
    "react-redux": "4.4.6",
    "react-router": "3.0.0",
    "react-router-redux": "4.0.7",
    "redux": "^3.5.2",
```

**Comment by Vishal-Isharani** [comment] 2016-12-31 06:10
@benjamine  i'm also facing this error, we have same packages

**Comment by owap** [comment] 2017-01-23 18:37
@benjamine I was able to resolve the issue by demoting `react-router-redux` to **4.0.5**
